server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: abcd1234
    key-store-type: PKCS12
    key-alias: springboot

spring:
  application:
    name: signaling-service
